CREATE TABLE IF NOT EXISTS teachers (
    id SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT,
    email TEXT,
    phone_number TEXT,
    date_of_birth DATE,
    gender TEXT,
    hire_date DATE,
    address TEXT
);