CREATE TABLE IF NOT EXISTS students (
    student_id SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roll_number TEXT,
    first_name TEXT NOT NULL,
    last_name TEXT,
    date_of_birth DATE,
    gender TEXT,
    email TEXT,
    phone_number TEXT,
    address TEXT,
    enrollment_date DATE,
    class_id SMALLINT NOT NULL REFERENCES classes(id),
    status TEXT
);